# .rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - guard-yaml.gemspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
